# This is an example mods.toml file. It contains the data relating to the loading mods.
modLoader = "javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GNU GPL 3.0"
[[mods]] #mandatory
modId = "botapi" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "BotApi" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://www.evolvefield.cn/" #optional
logoFile="BotApi.png" #optional
authors = "cnlimiter" #optional
description = '''
Adds chat linking between QQ and Minecraft and QQ commands to request server data.
'''
[[dependencies.botapi]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "SERVER"
[[dependencies.botapi]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
